version: '3'

networks:
    nginx-php-mysql:

services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - 8080:80
        volumes:
            - .:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        depends_on:
            - php-service
            - mysql-service
        networks:
            - nginx-php-mysql

    php-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php-container
        volumes:
            - .:/var/www/project
            - ./docker/env.conf:/var/www/project/.env.local
        networks:
            - nginx-php-mysql

    mysql-service:
        image: mysql:5.7
        container_name: mysql-container
        volumes:
            - ./docker/mysql:/var/lib/mysql
        command: --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - nginx-php-mysql



