parameters:
    locale: 'en'
    authors_on_page: '%env(AUTHORS_ON_PAGE)%'
    books_on_page: '%env(BOOKS_ON_PAGE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
